services:
  vllm_main:
    build:
      context: .
      dockerfile: ./Dockerfile.vllm
    ports:
      - "8000:8000"
    container_name: vllm_main
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]